In [71]:
from sklearn.cross_validation import train_test_split #allows spliting of data
from sklearn.naive_bayes import GaussianNB #to find a model
from sklearn.metrics import confusion_matrix #to generate confusion matrix

import pandas as pd
import numpy as np
#imports the file as a dataframe and uses the first row as the header
dataset= pd.read_csv('german_credit.csv',header=0) 
#gives the class info as the names of each column
CInfo = list(dataset)
print(CInfo)
no_obsv=len(dataset)
Features = dataset.values
Features = Features.transpose()
print(Features)
#split your data into training and test sets
FTrain, FTest, ClassTrain, ClassTest = train_test_split(Features, CInfo)
GNB_VARIABLE = GaussianNB()
#uses the training sets to generate a model
fit =GNB_VARIABLE.fit(FTrain, ClassTrain)
#creates a prediction based on the fit generated above
predicted = fit.predict(FTest)
#generates a confusion matrix based on the actual data versus the predicted data
result = confusion_matrix(ClassTest, predicted)
#prints the final confusion matrix
print(result)


['Creditability', 'Account Balance', 'Duration of Credit (month)', 'Payment Status of Previous Credit', 'Purpose', 'Credit Amount', 'Value Savings/Stocks', 'Length of current employment', 'Instalment per cent', 'Sex & Marital Status', 'Guarantors', 'Duration in Current address', 'Most valuable available asset', 'Age (years)', 'Concurrent Credits', 'Type of apartment', 'No of Credits at this Bank', 'Occupation', 'No of dependents', 'Telephone', 'Foreign Worker']
[[ 1  1  1 ...  0  0  0]
 [ 1  1  2 ...  4  2  1]
 [18  9 12 ... 21 12 30]
 ...
 [ 1  2  1 ...  1  1  1]
 [ 1  1  1 ...  2  2  1]
 [ 1  1  1 ...  1  1  1]]
[[0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]


SyntaxError: unexpected EOF while parsing (<ipython-input-1-f88395446a43>, line 2)