In [43]:
#allows us to use to load_digits dataset
from sklearn.datasets import load_digits
#allows us to split data int different sets
from sklearn.cross_validation import train_test_split
#classifier for data
from sklearn.naive_bayes import GaussianNB
#allows us to generate the confusion matrix
from sklearn.metrics import confusion_matrix

#loads the dataset
digits = load_digits()
#sets the target for the data
CInfo = digits.target
no_observation = len(digits.images)
#defines and shapes the data so that it can be split
Features = digits.images.reshape(no_observation,-1)

#splits up data so that we may find and test a pattern
FTrain, FTest, CTrain, CTest = train_test_split(Features, CInfo, random_state = 0)
#defines the classifer used
GNB_VARIABLE = GaussianNB()
#finds the pattern
fit = GNB_VARIABLE.fit(FTrain,CTrain)
#uses the pattern found above to make a prediction
predict= fit.predict(FTest)
#prints the confusion matrix for the prediction based on the test data
print (confusion_matrix(CTest, predict))

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 39  0  0  0  0  0  0  4  0]
 [ 0  7 20  2  0  0  0  0 15  0]
 [ 0  0  0 39  0  0  0  1  5  0]
 [ 0  1  0  0 31  0  0  6  0  0]
 [ 0  1  0  1  0 43  0  3  0  0]
 [ 0  0  1  0  0  0 51  0  0  0]
 [ 0  0  0  0  1  0  0 47  0  0]
 [ 0  6  0  1  0  1  0  2 38  0]
 [ 0  2  0  4  1  0  0  3  7 30]]


In [44]:
#imports necessary methods to create confusion matrix
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
import numpy as np

#loads the data
matrix = np.loadtxt('german_credit.csv', skiprows=1, delimiter=',')
#first column has the target for the model
CInfo=matrix[:,0]
no_obsv = len(matrix-1)
#the data to be examined
Feat= matrix.reshape(no_obsv,-1)

#splits up data to a 30%/70% split
FTrain, FTest, CTrain, CTest = train_test_split(Feat, CInfo, random_state = 0)
#defines the classifer used
GNB_VARIABLE = GaussianNB()
#finds the pattern
fit = GNB_VARIABLE.fit(FTrain, CTrain)
#uses the pattern found above to make a prediction
predict= fit.predict(FTest)
#prints the confusion matrix for the prediction based on the test data
print (confusion_matrix(CTest, predict))

[[ 83   0]
 [  0 167]]
